# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# rev: <tag_name> from github, f.e. https://github.com/PyCQA/bandit/tags


repos:
    # set pylint https://pylint.readthedocs.io/en/latest/user_guide/installation/pre-commit-integration.html
    -   repo: local  # it is possible to use Google style code https://github.com/google/styleguide/blob/gh-pages/pylintrc
        hooks:
            -   id: pylint
                name: pylint
                entry: pylint
                language: system
                types: [ python ]
                args: [
                    "--score=n",  # disable score points
                    "--disable=C0114, C0115, C0116",  # docstrings
                    "--disable=R0903, R0913",  # public items number
                    "--disable=W1203",  # lazy % formatting in logging functions: https://github.com/PyCQA/pylint/issues/2354
                    "--disable=C0413",  # wrong-import-position
                    "--extension-pkg-whitelist=orjson, pydantic",
                    "--variable-rgx=^[a-z][a-z0-9_]*$",  # by default you can't use ip, dp and etc
                    "--argument-rgx=^[a-z][a-z0-9_]*$",  # by default you can't use ip, dp and etc
                ]
    
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v1.1.1
        hooks:
            -   id: mypy
                additional_dependencies:
                    - 'pydantic'  # by default mypy doesn't understand pydantic
    
    -   repo: https://github.com/psf/black
        rev: 23.1.0
        hooks:
            -   id: black
                args: [
                    "--line-length=79"
                ]
    
    -   repo: https://github.com/pycqa/isort
        rev: 5.11.5
        hooks:
            -   id: isort